TccForum/Models/Entities/Resposta.cs
namespace TccForum.Models.Entities
{
    public class Resposta
    {
        public int Id { get; set; }
        public string Conteudo { get; set; }
        
        public int? UsuarioId { get; set; }
        public Usuario? Usuario { get; set; }
        
        public int PerguntaId { get; set; }
        public Pergunta Pergunta { get; set; }
    }
}

TccForum/Controllers/RespostaController.cs
using Microsoft.AspNetCore.Mvc;
using TccForum.Models.ViewModels;
using TccForum.Services.Resposta;

namespace TccForum.Controllers
{
    public class RespostaController : Controller
    {
        private readonly IRespostaInterface respostaInterface;

        public RespostaController(IRespostaInterface respostaInterface)
        {
            this.respostaInterface = respostaInterface;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Cadastrar(RespostaDaPerguntaCriacaoViewModel respostaDaPerguntaCriacaoViewModel)
        {
            await respostaInterface.CriarResposta(respostaDaPerguntaCriacaoViewModel);
            return RedirectToAction("Detalhar", "Pergunta", new { Id = respostaDaPerguntaCriacaoViewModel.PerguntaId });
        }
    }
}

TccForum/Views/Resposta/_Cadastrar.cshtml
@model RespostaDaPerguntaCriacaoViewModel

<form asp-controller="Resposta" asp-action="Cadastrar" method="post">
    <input type="hidden" asp-for="PerguntaId" />
    <textarea class="form-control shadow-none" type="text" asp-for="Conteudo"></textarea>
    <span class="text-danger" asp-validation-for="Conteudo"></span>
    <button type="submit" class="btn btn-primary mt-1">Responder</button>
</form>

TccForum/Views/Resposta/_Listar.cshtml
@model IEnumerable<Resposta>

@if (Model != null && Model.Any())
{
    foreach (var resposta in Model)
    {
        <div class="card border-0 px-gutter-2 py-gutter-1 flex-row">
            <img class="m-1" src="/assets/no-avatar.jpg" width="46" height="46" />
            <div class="card-body p-1">
                <h6 class="h6 mb-gutter-2 mb-gutter-sm-1">@(resposta.Usuario.PrimeiroNome + " " + resposta.Usuario.UltimoNome)</h6>
                <p class="text-secondary mt-1 mt-gutter-sm-0">@resposta.Conteudo</p>
            </div>
        </div>
        <hr class="m-0" />
    }
}
else
{
    <div class="mb-1">
        <p>Ainda não há respostas para essa pergunta</p>
    </div>
}