TccForum/Controllers/PerguntaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TccForum.Models.ViewModels;
using TccForum.Services.Pergunta;

namespace TccForum.Controllers
{
    public class PerguntaController : Controller
    {
        private readonly IPerguntaInterface perguntaInterface;

        public PerguntaController(IPerguntaInterface perguntaInterface)
        {
            this.perguntaInterface = perguntaInterface;
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.Nome = HttpContext.User.Identity.Name;
            var perguntas = await perguntaInterface.BuscarTodasAsPerguntas();
            return View(perguntas);
        }

        [Authorize(Policy = "UsuarioPremium")]
        public IActionResult Cadastrar() => View();

        [HttpPost]
        public async Task<IActionResult> Cadastrar(
            PerguntaCriacaoViewModel perguntaViewModel,
            IFormFile capaDaPergunta)
        {
            await perguntaInterface.CriarPergunta(perguntaViewModel, capaDaPergunta);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Detalhar(int id)
        {
            var pergunta = await perguntaInterface.BuscarPerguntaComRespostasPorId(id);
            return View(pergunta);
        }

        public async Task<IActionResult> Editar(int id)
        {
            var pergunta = await perguntaInterface.BuscarPerguntaParaEdicaoPorId(id);
            return View(pergunta);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(
            Models.Entities.Pergunta pergunta,
            IFormFile? capaDaPergunta)
        {
            await perguntaInterface.EditarPergunta(pergunta, capaDaPergunta);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Remover(int id)
        {
            await perguntaInterface.RemoverPergunta(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

TccForum/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TccForum</title>
    @* bootstrap *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @* postboot*@
    <link href="~/postboot/css/postboot.min.css" rel="stylesheet" />
    <script src="~/postboot/js/postboot.min.js"></script>
    @* jquery *@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TccForum.styles.css" asp-append-version="true" />
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TccForum</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Início</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pergunta" asp-action="Index">Perguntas</a>
                        </li>
                    </ul>
                    @await Html.PartialAsync("_UsuarioLogado")
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid container-xl">
        <div class="row">
            <div class="col-md col-md-auto col-lg-2 bg-dark-80"></div>
            <div class="col-12 col-md-9 col-lg-8">
                <main role="main">
                    @RenderBody()
                </main>
            </div>
            <div class="col-lg-2 d-none d-lg-block bg-dark-80"></div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TccForum - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TccForum/Views/Shared/_UsuarioLogado.cshtml
@if (Context.User.Identity.Name != null)
{
    <ul class="nav navbar-nav navbar-right">
        <form asp-controller="Account" asp-action="LogOut" method="post" id="logOutForm" class="navbar-right">
            <li class="nav-link">Olá, @Context.User.Identity.Name!</li>
            <button type="submit" class="btn btn-link nav-link">| Sair</button>
        </form>
    </ul>
}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li><a class="nav-link text-dark" asp-controller="Account" asp-action="Cadastrar">Criar conta</a></li>
        <li><a class="nav-link text-dark" asp-controller="Account" asp-action="Login">Acessar conta</a></li>
    </ul>
}